def get_base_comments() -> list[str]:
    return [
        "Esse novo iPhone 17 tá simplesmente surreal! O desempenho é absurdo 🔥",
        "Achei o design bem parecido com o do 16, esperava algo mais inovador.",
        "Alguém sabe se o modelo base ainda vem com apenas 128GB?",
        "A câmera em ambientes noturnos tá MUITO melhor, parece até profissional! As fotos saem super nítidas mesmo com pouca luz.",
        "Senti que o preço tá meio salgado demais, mesmo pro padrão Apple 😅",
        "O novo chip A19 é insano, o celular nem esquenta rodando jogos pesados.",
        "Será que finalmente vale a pena trocar meu iPhone 14 Pro por esse?",
        "O modo retrato tá mais natural, não borra tanto o fundo como antes. As selfies também estão com mais detalhes!",
        "A tela com 120Hz ficou ainda mais fluida, é outra experiência!",
        "Não gostei da remoção total das bordas retas, preferia o design antigo.",
        "A bateria realmente dura mais, consegui quase dois dias de uso normal sem precisar carregar 🔋",
        "A função de IA nas fotos é incrível, ajusta cor, brilho e nitidez automaticamente 😍",
        "Podiam ter melhorado o carregamento rápido… ainda muito lento comparado a outras marcas.",
        "Com esse preço, era pra vir com um carregador de ouro 😂",
        "O novo acabamento fosco é lindo e parece mais resistente a marcas de dedo.",
        "Vi que agora dá pra gravar vídeos em 8K — a qualidade é insana, muito nítida!",
        "A Apple sempre consegue deixar o sistema ainda mais fluido, impressionante.",
        "Achei o som estéreo mais imersivo, perfeito pra ver filmes ou ouvir música.",
        "A nova cor azul titânio é simplesmente perfeita 😍",
        "Sinceramente, esperava mais diferença entre o 17 e o 16 Pro Max.",
        "A autonomia da bateria melhorou demais, aguenta o dia inteiro com brilho alto.",
        "As fotos com zoom estão muito mais detalhadas, mesmo de longe a imagem fica limpa.",
        "O modo retrato da câmera frontal ficou top, a pele sai com um tom bem natural.",
        "A câmera ultra-angular capta muito mais luz agora, as fotos noturnas ficaram lindas.",
        "O carregamento sem fio parece um pouco mais rápido, mas ainda podia melhorar.",
        "Notei que o celular consome pouca bateria mesmo jogando ou filmando vídeos longos.",
        "A estabilização da câmera tá absurda, dá pra gravar andando sem tremer nada.",
        "O HDR das fotos tá mais equilibrado, cores bem vivas sem exagero.",
        "A bateria demora um pouco pra carregar, mas a duração compensa.",
        "No geral, a câmera e a bateria foram as melhores melhorias desse modelo!",
    ]